services:
  app:
    build:
      context: ./Advanced-ATS-Resume-Checker
    ports:
      - "5000:5000"
    env_file:
      - ./Advanced-ATS-Resume-Checker/.env
    environment:
      - FLASK_APP=app.py  # Runs app.py

  frontend:
    build:
      context: ./React_FrontEnd
    ports:
      - "3000:3000"
    depends_on:
      - app
